[build]
  publish = "build"  # Replace "build" with the directory where your built files are located (e.g., "dist")
  command = "npm run build"  # The build command (for example, "npm run build" for React)

# Define redirects to ensure the /callback route works properly
[[redirects]]
  from = "/callback"
  to = "/callback/index.html"
  status = 200
  force = true